//software accessible registers
//INPUT REGS 

`SWREG_W(KNN_RESET,            1, 0) 
`SWREG_W(KNN_START,            1, 0) 
`SWREG_W(KNN_VALID_IN,         `KNN_VALID_W, 0)
`SWREG_W(KNN_TEST_PT,          `WDATA_W, 0) 

`SWREG_W(KNN_DATA_PT1,          `WDATA_W, 0)
`SWREG_W(KNN_DATA_PT2,          `WDATA_W, 0)
`SWREG_W(KNN_DATA_PT3,          `WDATA_W, 0)
`SWREG_W(KNN_DATA_PT4,          `WDATA_W, 0)
`SWREG_W(KNN_DATA_PT5,          `WDATA_W, 0)
`SWREG_W(KNN_DATA_PT6,          `WDATA_W, 0)
`SWREG_W(KNN_DATA_PT7,          `WDATA_W, 0)
`SWREG_W(KNN_DATA_PT8,          `WDATA_W, 0)

`SWREG_W(KNN_SAMPLE,            1, 0) 

//OUTPUT REGS

`SWREG_R(KNN_VALID_OUT,        1, 0)
`SWREG_R(KNN_KN1,`WDATA_W,0)
`SWREG_R(KNN_KN2,`WDATA_W,0)
`SWREG_R(KNN_KN3,`WDATA_W,0)
`SWREG_R(KNN_KN4,`WDATA_W,0)
`SWREG_R(KNN_KN5,`WDATA_W,0)
`SWREG_R(KNN_KN6,`WDATA_W,0)
	
`SWREG_R(KNN_IN1, `K_NUM_DATA_PTS_BIT,0)
`SWREG_R(KNN_IN2, `K_NUM_DATA_PTS_BIT,0)
`SWREG_R(KNN_IN3, `K_NUM_DATA_PTS_BIT,0)
`SWREG_R(KNN_IN4, `K_NUM_DATA_PTS_BIT,0)
`SWREG_R(KNN_IN5, `K_NUM_DATA_PTS_BIT,0)
`SWREG_R(KNN_IN6, `K_NUM_DATA_PTS_BIT,0)

